stages:
    - lint
    - build

default:
    before_script:
        - pod update
    tags:
        - macos-xcode26
    interruptible: true

variables:
    LANG: "en_US.UTF-8"
    LC_ALL: "en_US.UTF-8"

## Shared configuration

.job-base:
    only:
        refs:
            - master
            - merge_requests

.build-base:
    script:
        - xcodebuild -version
        - xcodebuild -verbose -workspace "VLC.xcworkspace" -scheme "$BUILD_SCHEME" -configuration "Debug" clean build -destination "$BUILD_DESTINATION" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

## Lint

lint:
    extends: .job-base
    stage: lint
    script:
        - ./Pods/SwiftLint/swiftlint --config Buildsystem/swiftlint.yml

## Builds

### iOS Builds

iOS 26.x:
    extends:
        - .job-base
        - .build-base
    stage: build
    variables:
        BUILD_SCHEME: "VLC-iOS"
        BUILD_DESTINATION: "platform=iOS Simulator,name=iPhone Air,OS=26.2"

iOS 15.x:
    extends:
        - .job-base
        - .build-base
    stage: build
    variables:
        BUILD_SCHEME: "VLC-iOS"
        BUILD_DESTINATION: "platform=iOS Simulator,name=iPhone 13,OS=15.4"

### tvOS Builds

tvOS 15.x:
    extends:
        - .job-base
        - .build-base
    tags:
        - macos-xcode26
    stage: build
    variables:
        BUILD_SCHEME: "VLC-tvOS"
        BUILD_DESTINATION: "platform=tvOS Simulator,name=Apple TV,OS=15.4"

### visionOS Builds

visionOS 1.x:
    extends:
        - .job-base
        - .build-base
    tags:
        - macos-xcode26
    stage: build
    variables:
        BUILD_SCHEME: "VLC-visionOS"
        BUILD_DESTINATION: "platform=xrOS Simulator,name=Apple Vision Pro,OS=1.2"

### watchOS Builds
watchOS 10.x:
    extends:
        - .job-base
        - .build-base
    stage: build
    variables:
        BUILD_SCHEME: "VLC-watchOS"
        BUILD_DESTINATION: "platform=watchOS Simulator,name=Apple Watch Series 9 (45mm),OS=10.5"
